export enum ErrorCode {
  // HTTP Standard Errors
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNPROCESSABLE_ENTITY = 'VALIDATION_ERROR',
  TOO_MANY_REQUESTS = 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  
  // Authentication & Authorization
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_TOKEN = 'INVALID_TOKEN',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  INVALID_SESSION = 'INVALID_SESSION',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  
  // Resource Errors
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_DELETED = 'RESOURCE_DELETED',
  
  // Validation Errors
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  
  // Business Logic Errors
  OPERATION_FAILED = 'OPERATION_FAILED',
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  
  // External Service Errors
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  
  // Database Errors
  DATABASE_ERROR = 'DATABASE_ERROR',
  QUERY_FAILED = 'QUERY_FAILED',
  
  // Queue Errors
  QUEUE_ERROR = 'QUEUE_ERROR',
  QUEUE_NOT_FOUND = 'QUEUE_NOT_FOUND',
  QUEUE_OPERATION_FAILED = 'QUEUE_OPERATION_FAILED',
  JOB_FAILED = 'JOB_FAILED',
  JOB_NOT_FOUND = 'JOB_NOT_FOUND',
  JOB_ADD_FAILED = 'JOB_ADD_FAILED',
  
  // Analytics Errors
  LOG_PROCESSING_FAILED = 'LOG_PROCESSING_FAILED',
  ANALYTICS_SCHEDULING_FAILED = 'ANALYTICS_SCHEDULING_FAILED',
  
  // Rule Errors
  RULE_NOT_FOUND = 'RULE_NOT_FOUND',
  RULE_CREATION_FAILED = 'RULE_CREATION_FAILED',
  RULE_UPDATE_FAILED = 'RULE_UPDATE_FAILED',
  RULE_DELETION_FAILED = 'RULE_DELETION_FAILED',
  
  // Policy Errors
  POLICY_NOT_FOUND = 'POLICY_NOT_FOUND',
  POLICY_CREATION_FAILED = 'POLICY_CREATION_FAILED',
  POLICY_UPDATE_FAILED = 'POLICY_UPDATE_FAILED',
  POLICY_EVALUATION_FAILED = 'POLICY_EVALUATION_FAILED',
  POLICY_LOG_FAILED = 'POLICY_LOG_FAILED',
  
  // Webhook Errors
  WEBHOOK_INVALID_SIGNATURE = 'WEBHOOK_INVALID_SIGNATURE',
  WEBHOOK_MISSING_HEADERS = 'WEBHOOK_MISSING_HEADERS',
  WEBHOOK_HANDLING_FAILED = 'WEBHOOK_HANDLING_FAILED',
  WEBHOOK_EVENT_NOT_SUPPORTED = 'WEBHOOK_EVENT_NOT_SUPPORTED'
}
